# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categorie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
