# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='cat_image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='categorie_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
